---
title: "Creating Cooccurrence for RV Bacteria OTUs"
---

```{r setup, include=FALSE}
set.seed(1390)
knitr::opts_chunk$set(echo = TRUE)
```

```{r load_packages, message = FALSE, warning = FALSE}
library(phyloseq, warn.conflicts = FALSE)
library(biomformat, warn.conflicts = FALSE)
```

```{r load_data}
bacteria_otus <- as.data.frame(as.matrix(biom_data(read_biom("../data/bacteria/otus_table_full.biom"))))
colnames(bacteria_otus) <- paste("X",colnames(bacteria_otus),sep="")
```

## Sample Data
```{r}
si <- read.csv("../data/bacteria/Data_for_bacterial_OTUs.csv")[,-1]
colnames(si) <- c("Flower", "Treatment", "sample.name")
rownames(si) <- paste("X", si$Flower, sep="")
si <- si[,-1]
```

```{r taxonomy}
tax_bac <- read.delim("../data/bacteria/otus_repsetOUT_tax_assignments.txt",sep = "\t", header = FALSE, row.names=1)
colnames(tax_bac) <- c("kingdom","phylum","class","order","family","genus","species")
tax_bac <- tax_bac[,-c(8,9)]
```

```{r phyloseq}
bacteria_phylo <- phyloseq(otu_table(as.matrix(bacteria_otus), taxa_are_rows=T), tax_table(as.matrix(tax_bac)), sample_data(si))
saveRDS(bacteria_phylo, "../data/bacteria/bacteria_phylo.RDS")
```

```{r prep-cooccurr}
trt <- as.character(sample_data(bacteria_phylo)$Treatment)
f_table <- cbind(trt, t(otu_table(bacteria_phylo)))
write.csv(f_table, "../data/bacteria/RVbac_fcoocurr_input.csv")
```
