---
title: "Creating Cooccurrence for our Bacteria OTUs"
---

```{r setup, include=FALSE}
set.seed(1390)
knitr::opts_chunk$set(echo = TRUE)
```

```{r load_packages, message = FALSE, warning = FALSE}
library(phyloseq, warn.conflicts = FALSE)
```

The otu tables were made in our pipeline using cd-hit to call clusters (OTUS) and custom scripts for formatting the table.

```{r load_data}
fungi_otus <- read.table("../data/yeast/fungi_cdhit_otu_table_wide_97.txt", header=TRUE, row.names=1)
quantile(colSums(fungi_otus))
sum(colSums(fungi_otus) < 500)/ ncol(fungi_otus)
fungi_otus <- fungi_otus[,colSums(fungi_otus) >= 500]
```

## Combining OTU data with Taxonomy

Taxonomy classifications were done using the rdp-classifier program.

```{r}
si <- read.csv("../data/bacteria/Data_for_bacterial_OTUs.csv")[,-1]
colnames(si) <- c("Flower", "Treatment", "sample.name")
rownames(si) <- paste("X", si$Flower, sep="")
si <- si[,-1]
```

```{r taxonomy}
tax_fun <- read.delim("../data/yeast/fungi_cdhit_taxa_table_w_repseq_97.txt", sep="\t", header = TRUE, row.names=2, fill = TRUE)[,-1]
```

```{r phyloseq}
fungi_phylo <- phyloseq(otu_table(as.matrix(fungi_otus), taxa_are_rows=T), tax_table(as.matrix(tax_fun)), sample_data(si))
saveRDS(fungi_phylo, "../data/yeast/fungal_phyloseq.RDS")
```

```{r prep-cooccurr}
trt <- as.character(sample_data(fungi_phylo)$Treatment)
f_table <- cbind(trt, t(otu_table(fungi_phylo)))
write.csv(f_table, "../data/yeast/fun_fcoocurr_input.csv")
```